use sqlparser::ast::{
    AlterColumnOperation, AlterTableOperation, ColumnDef, ColumnOption, ColumnOptionDef,
    CopyTarget, CreateTableOptions, DataType, DeclareType, Expr, GeneratedAs, IndexOption,
    SequenceOptions, Set, SqlOption, Statement, TableConstraint, TransactionIsolationLevel,
    TransactionMode, UnaryOperator, Value, ValueWithSpan,
};
use sqlparser::tokenizer::Span;

use crate::lint::{Diagnostic, FixResult, LintRule};

use super::{find_line, find_line_any};

/// Construct a `CACHE 1` sequence option — the safe default for DSQL.
fn cache_1_option() -> SequenceOptions {
    SequenceOptions::Cache(Expr::Value(ValueWithSpan {
        value: Value::Number("1".to_string(), false),
        span: Span::empty(),
    }))
}

fn error(
    rule: LintRule,
    line: usize,
    message: impl Into<String>,
    suggestion: impl Into<String>,
    fix_result: FixResult,
) -> Diagnostic {
    Diagnostic {
        rule,
        line,
        statement: String::new(),
        message: message.into(),
        suggestion: suggestion.into(),
        fix_result,
    }
}

/// Check a single column definition for unsupported types and constraints.
/// `in_alter_table`: true when called from ALTER TABLE ADD COLUMN context.
/// DSQL does not allow constraints on ALTER TABLE ADD COLUMN, so fixes that
/// add constraints (e.g. SERIAL → IDENTITY) must be Unfixable there.
fn check_column(
    col: &mut ColumnDef,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
    in_alter_table: bool,
) {
    let col_name_lower = col.name.to_string().to_lowercase();

    // SERIAL variants
    if let DataType::Custom(name, _) = &col.data_type {
        let type_str = name.to_string().to_uppercase();
        if matches!(
            type_str.as_str(),
            "SERIAL" | "SERIAL4" | "BIGSERIAL" | "SERIAL8" | "SMALLSERIAL" | "SERIAL2"
        ) {
            if in_alter_table {
                diagnostics.push(error(
                    LintRule::SerialType,
                    find_line(raw_sql, &type_str.to_lowercase()),
                    format!(
                        "Column `{}` uses {type_str}, which is not supported in DSQL.",
                        col.name
                    ),
                    "DSQL does not support ALTER TABLE ADD COLUMN with constraints. Define identity columns at table creation time.",
                    FixResult::Unfixable,
                ));
            } else {
                col.data_type = DataType::BigInt(None);
                col.options.push(ColumnOptionDef {
                    name: None,
                    option: ColumnOption::Generated {
                        generated_as: GeneratedAs::ByDefault,
                        sequence_options: Some(vec![cache_1_option()]),
                        generation_expr: None,
                        generation_expr_mode: None,
                        generated_keyword: false,
                    },
                });
                diagnostics.push(error(
                    LintRule::SerialType,
                    find_line(raw_sql, &type_str.to_lowercase()),
                    format!(
                        "Column `{}` uses {type_str}, which is not supported in DSQL.",
                        col.name
                    ),
                    "Use `BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)` instead.",
                    FixResult::FixedWithWarning(format!("Replaced {} with BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) on column `{}` — verify application code handles the wider type range", type_str, col.name)),
                ));
            }
        }
    }

    // JSON / JSONB
    let type_name = match &col.data_type {
        DataType::JSON => Some("JSON"),
        DataType::JSONB => Some("JSONB"),
        _ => None,
    };
    if let Some(type_str) = type_name {
        col.data_type = DataType::Text;
        diagnostics.push(error(
            LintRule::JsonType,
            find_line(raw_sql, &type_str.to_lowercase()),
            format!(
                "Column `{}` uses {type_str}, which is not supported in DSQL.",
                col.name
            ),
            "Use TEXT to store JSON data as a string.",
            FixResult::Fixed(format!(
                "Replaced {} with TEXT on column `{}`",
                type_str, col.name
            )),
        ));
    }

    // Array types
    if matches!(&col.data_type, DataType::Array(_)) {
        diagnostics.push(error(
            LintRule::ArrayType,
            find_line(raw_sql, &col_name_lower),
            format!(
                "Column `{}` uses an array type, which is not supported in DSQL.",
                col.name
            ),
            "Use a join table for relational data, or store as JSON text.",
            FixResult::Unfixable,
        ));
    }

    // Identity checks — type and CACHE fixes.
    for opt_def in &mut col.options {
        if let ColumnOption::Generated {
            generated_as: GeneratedAs::Always | GeneratedAs::ByDefault,
            sequence_options,
            ..
        } = &mut opt_def.option
        {
            if in_alter_table {
                diagnostics.push(error(
                    LintRule::IdentityType,
                    find_line(raw_sql, &col_name_lower),
                    format!(
                        "Column `{}` uses GENERATED AS IDENTITY, which is not supported in ALTER TABLE ADD COLUMN in DSQL.",
                        col.name
                    ),
                    "DSQL does not support ALTER TABLE ADD COLUMN with constraints. Define identity columns at table creation time.",
                    FixResult::Unfixable,
                ));
                break;
            }
            if !matches!(&col.data_type, DataType::BigInt(_) | DataType::Int8(_)) {
                let old_type = col.data_type.to_string();
                col.data_type = DataType::BigInt(None);
                diagnostics.push(error(
                    LintRule::IdentityType,
                    find_line(raw_sql, &col_name_lower),
                    format!(
                        "Identity column `{}` must use BIGINT type in DSQL. Found: {old_type}.",
                        col.name
                    ),
                    "Use BIGINT GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY (CACHE ...).",
                    FixResult::FixedWithWarning(format!("Changed identity column `{}` type from {old_type} to BIGINT — verify application code handles the wider 8-byte range", col.name)),
                ));
            }
            if let Some(seq_opts) = sequence_options {
                validate_cache_options(LintRule::IdentityCache, seq_opts, raw_sql, diagnostics);
            }
        }
    }

    // FK removal — retain everything that's NOT a foreign key
    let col_name = col.name.to_string();
    col.options.retain(|opt_def| {
        if matches!(opt_def.option, ColumnOption::ForeignKey(_)) {
            diagnostics.push(error(
                LintRule::ForeignKey,
                find_line(raw_sql, &col_name_lower),
                format!("Column `{}` has a FOREIGN KEY (REFERENCES) constraint, which is not supported in DSQL.", col_name),
                "Remove the REFERENCES clause. Enforce referential integrity in application code.",
                FixResult::FixedWithWarning(format!("Removed FOREIGN KEY constraint from column `{}`", col_name)),
            ));
            false
        } else {
            true
        }
    });
}

pub(crate) fn check(stmt: &mut Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateTable(ct) = stmt {
        for col in &mut ct.columns {
            check_column(col, raw_sql, diagnostics, false);
        }

        ct.constraints.retain(|constraint| {
            if matches!(constraint, TableConstraint::ForeignKey(_)) {
                diagnostics.push(error(
                    LintRule::ForeignKey,
                    find_line(raw_sql, "foreign key"),
                    "Table-level FOREIGN KEY constraint is not supported in DSQL.",
                    "Remove the FOREIGN KEY constraint. Enforce referential integrity in application code.",
                    FixResult::FixedWithWarning("Removed table-level FOREIGN KEY constraint".into()),
                ));
                false
            } else {
                true
            }
        });

        if ct.temporary {
            ct.temporary = false;
            diagnostics.push(error(
                LintRule::TempTable,
                find_line_any(raw_sql, &["temporary", "temp"]),
                "TEMPORARY tables are not supported in DSQL.",
                "Use regular tables or application-level caching.",
                FixResult::FixedWithWarning("Removed TEMPORARY keyword — table is now persistent and visible to all sessions".into()),
            ));
        }

        if ct.partition_by.is_some() {
            ct.partition_by = None;
            diagnostics.push(error(
                LintRule::PartitionBy,
                find_line(raw_sql, "partition by"),
                "PARTITION BY is not supported in DSQL.",
                "Omit — DSQL manages distribution automatically.",
                FixResult::FixedWithWarning("Removed PARTITION BY clause".into()),
            ));
        }

        // INHERITS clause
        if ct.inherits.as_ref().is_some_and(|v| !v.is_empty()) {
            ct.inherits = None;
            diagnostics.push(error(
                LintRule::Inherits,
                find_line(raw_sql, "inherits"),
                "INHERITS clause is not supported in DSQL.",
                "Flatten the table hierarchy or use application-layer inheritance patterns.",
                FixResult::FixedWithWarning("Removed INHERITS clause".into()),
            ));
        }

        // CREATE TABLE AS / SELECT INTO
        if ct.query.is_some() {
            diagnostics.push(error(
                LintRule::CreateTableAs,
                find_line_any(raw_sql, &["as select", "as\n", "as"]),
                "CREATE TABLE AS (SELECT ...) is not supported in DSQL.",
                "Create the table with explicit column definitions, then INSERT INTO ... SELECT ....",
                FixResult::Unfixable,
            ));
        }

        // TABLESPACE clause
        match &mut ct.table_options {
            CreateTableOptions::With(opts)
            | CreateTableOptions::Options(opts)
            | CreateTableOptions::Plain(opts)
            | CreateTableOptions::TableProperties(opts) => {
                let len_before = opts.len();
                opts.retain(|o| !matches!(o, SqlOption::TableSpace(_)));
                if opts.len() < len_before {
                    diagnostics.push(error(
                        LintRule::Tablespace,
                        find_line(raw_sql, "tablespace"),
                        "TABLESPACE clause is not supported in DSQL.",
                        "Remove the TABLESPACE clause. DSQL manages storage automatically.",
                        FixResult::FixedWithWarning("Removed TABLESPACE clause".into()),
                    ));
                }
            }
            CreateTableOptions::None => {}
        }
    }

    check_alter_table(stmt, raw_sql, diagnostics);
    check_truncate(stmt, raw_sql, diagnostics);
    check_create_index(stmt, raw_sql, diagnostics);
    check_create_sequence(stmt, raw_sql, diagnostics);
    check_unsupported_statements(stmt, raw_sql, diagnostics);
    check_add_column_constraints(stmt, raw_sql, diagnostics);
    check_transaction_isolation(stmt, raw_sql, diagnostics);
    check_sequence_cache_missing(stmt, raw_sql, diagnostics);
    check_identity_cache_missing(stmt, raw_sql, diagnostics);
    check_alter_table_operations(stmt, raw_sql, diagnostics);
}

fn check_alter_table(stmt: &mut Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    let Statement::AlterTable(alter_table) = stmt else {
        return;
    };

    // Mutable pass: remove FK constraints
    alter_table.operations.retain(|op| {
        match op {
            AlterTableOperation::AddConstraint {
                constraint: TableConstraint::ForeignKey(_),
                ..
            } => {
                diagnostics.push(error(
                    LintRule::ForeignKey,
                    find_line(raw_sql, "foreign key"),
                    "ALTER TABLE ADD CONSTRAINT with FOREIGN KEY is not supported in DSQL.",
                    "Remove the FOREIGN KEY constraint. Enforce referential integrity in application code.",
                    FixResult::FixedWithWarning(
                        "Removed ALTER TABLE ADD FOREIGN KEY constraint".into(),
                    ),
                ));
                false
            }
            _ => true,
        }
    });

    // Mutable pass: check columns (needs &mut for fix mutations) and
    // read-only checks for everything else.
    for op in &mut alter_table.operations {
        match op {
            AlterTableOperation::AddColumn { column_def, .. } => {
                check_column(column_def, raw_sql, diagnostics, true);
            }
            AlterTableOperation::AddConstraint {
                constraint: TableConstraint::PrimaryKeyUsingIndex { .. },
                ..
            } => {
                diagnostics.push(error(
                    LintRule::UnsupportedAlterTableOp,
                    find_line(raw_sql, "using index"),
                    "PRIMARY KEY USING INDEX is not supported in DSQL.",
                    "Create a PRIMARY KEY constraint directly instead of promoting an index.",
                    FixResult::Unfixable,
                ));
            }
            AlterTableOperation::AddConstraint {
                constraint: TableConstraint::UniqueUsingIndex { .. },
                ..
            } => {
                diagnostics.push(error(
                    LintRule::UnsupportedAlterTableOp,
                    find_line(raw_sql, "using index"),
                    "UNIQUE USING INDEX is not supported in DSQL.",
                    "Create a UNIQUE constraint directly instead of promoting an index.",
                    FixResult::Unfixable,
                ));
            }
            // Row-Level Security
            AlterTableOperation::EnableRowLevelSecurity
            | AlterTableOperation::DisableRowLevelSecurity
            | AlterTableOperation::ForceRowLevelSecurity
            | AlterTableOperation::NoForceRowLevelSecurity => {
                diagnostics.push(error(
                    LintRule::UnsupportedAlterTableOp,
                    find_line(raw_sql, "row level security"),
                    format!("ALTER TABLE {op} is not supported in DSQL."),
                    "Implement row-level access control in the application layer.",
                    FixResult::Unfixable,
                ));
            }
            // Triggers
            AlterTableOperation::EnableTrigger { .. }
            | AlterTableOperation::DisableTrigger { .. }
            | AlterTableOperation::EnableAlwaysTrigger { .. }
            | AlterTableOperation::EnableReplicaTrigger { .. } => {
                diagnostics.push(error(
                    LintRule::UnsupportedAlterTableOp,
                    find_line(raw_sql, "trigger"),
                    format!("ALTER TABLE {op} is not supported in DSQL."),
                    "Implement trigger logic in the application layer.",
                    FixResult::Unfixable,
                ));
            }
            // Replica identity
            AlterTableOperation::ReplicaIdentity { .. } => {
                diagnostics.push(error(
                    LintRule::UnsupportedAlterTableOp,
                    find_line(raw_sql, "replica identity"),
                    "ALTER TABLE REPLICA IDENTITY is not supported in DSQL.",
                    "DSQL does not support logical replication. Remove this statement.",
                    FixResult::Unfixable,
                ));
            }
            // VALIDATE CONSTRAINT
            AlterTableOperation::ValidateConstraint { name } => {
                diagnostics.push(error(
                    LintRule::UnsupportedAlterTableOp,
                    find_line(raw_sql, "validate constraint"),
                    format!("ALTER TABLE VALIDATE CONSTRAINT '{name}' is not supported in DSQL."),
                    "Add constraints as valid at creation time.",
                    FixResult::Unfixable,
                ));
            }
            // Rewrite rules
            AlterTableOperation::EnableRule { .. }
            | AlterTableOperation::DisableRule { .. }
            | AlterTableOperation::EnableAlwaysRule { .. }
            | AlterTableOperation::EnableReplicaRule { .. } => {
                diagnostics.push(error(
                    LintRule::UnsupportedAlterTableOp,
                    find_line(raw_sql, "rule"),
                    format!("ALTER TABLE {op} is not supported in DSQL."),
                    "Remove rewrite rules. Implement logic in the application layer.",
                    FixResult::Unfixable,
                ));
            }
            _ => {}
        }
    }
}

/// ALTER TABLE ADD COLUMN with inline DEFAULT or NOT NULL.
fn check_add_column_constraints(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let Statement::AlterTable(alter_table) = stmt else {
        return;
    };

    for op in &alter_table.operations {
        if let AlterTableOperation::AddColumn { column_def, .. } = op {
            let has_default_or_not_null = column_def
                .options
                .iter()
                .any(|opt| matches!(opt.option, ColumnOption::Default(_) | ColumnOption::NotNull));
            if has_default_or_not_null {
                diagnostics.push(error(
                    LintRule::AddColumnConstraint,
                    find_line(raw_sql, &column_def.name.value.to_lowercase()),
                    format!(
                        "ADD COLUMN '{}' with inline DEFAULT or NOT NULL constraint is not supported in DSQL.",
                        column_def.name.value
                    ),
                    "Split into steps: CREATE TABLE with the column, or ADD COLUMN without constraints then backfill.",
                    FixResult::Unfixable,
                ));
            }
        }
    }
}

/// Unsupported ALTER TABLE operations.
fn check_alter_table_operations(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let Statement::AlterTable(alter_table) = stmt else {
        return;
    };

    for op in &alter_table.operations {
        let (msg, suggestion, needle): (String, &str, &str) = match op {
            AlterTableOperation::DropColumn { column_names, .. } => {
                let names: Vec<_> = column_names.iter().map(|n| n.to_string()).collect();
                (
                    format!(
                        "ALTER TABLE DROP COLUMN ({}) is not supported in DSQL.",
                        names.join(", ")
                    ),
                    "Recreate the table without the column, then migrate data.",
                    "drop column",
                )
            }
            AlterTableOperation::AlterColumn {
                column_name,
                op: alter_op,
            } => match alter_op {
                AlterColumnOperation::SetDataType { .. } => (
                    format!("ALTER COLUMN '{column_name}' TYPE is not supported in DSQL."),
                    "Recreate the table with the desired column type.",
                    "alter column",
                ),
                AlterColumnOperation::SetNotNull => (
                    format!(
                        "ALTER COLUMN '{column_name}' SET NOT NULL is not supported in DSQL."
                    ),
                    "Add NOT NULL at table creation time.",
                    "not null",
                ),
                AlterColumnOperation::DropNotNull => (
                    format!(
                        "ALTER COLUMN '{column_name}' DROP NOT NULL is not supported in DSQL."
                    ),
                    "Recreate the table if needed.",
                    "not null",
                ),
                AlterColumnOperation::SetDefault { .. } => (
                    format!(
                        "ALTER COLUMN '{column_name}' SET DEFAULT is not supported in DSQL."
                    ),
                    "Set default at table creation time.",
                    "set default",
                ),
                AlterColumnOperation::DropDefault => (
                    format!(
                        "ALTER COLUMN '{column_name}' DROP DEFAULT is not supported in DSQL."
                    ),
                    "Recreate the table if needed.",
                    "drop default",
                ),
                AlterColumnOperation::AddGenerated { .. } => (
                    format!(
                        "ALTER COLUMN '{column_name}' ADD GENERATED AS IDENTITY is not supported in DSQL."
                    ),
                    "Define identity columns at table creation time.",
                    "identity",
                ),
            },
            AlterTableOperation::AddConstraint { constraint, .. } => match constraint {
                TableConstraint::Check(_) => (
                    "ALTER TABLE ADD CHECK constraint is not supported in DSQL.".to_string(),
                    "Add CHECK constraints at table creation time.",
                    "add constraint",
                ),
                TableConstraint::Unique(_) => (
                    "ALTER TABLE ADD UNIQUE constraint is not supported in DSQL.".to_string(),
                    "Add UNIQUE constraints at table creation time.",
                    "add constraint",
                ),
                _ => continue,
            },
            AlterTableOperation::DropConstraint { name, .. } => (
                format!("ALTER TABLE DROP CONSTRAINT '{name}' is not supported in DSQL."),
                "Recreate the table without the constraint.",
                "drop constraint",
            ),
            _ => continue,
        };
        diagnostics.push(error(
            LintRule::UnsupportedAlterTableOp,
            find_line(raw_sql, needle),
            msg,
            suggestion,
            FixResult::Unfixable,
        ));
    }
}

fn check_create_index(stmt: &mut Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    let Statement::CreateIndex(ci) = stmt else {
        return;
    };

    if ci.concurrently {
        ci.concurrently = false;
        ci.r#async = true;
        diagnostics.push(error(
            LintRule::IndexConcurrently,
            find_line(raw_sql, "concurrently"),
            "CREATE INDEX CONCURRENTLY is not supported in DSQL.",
            "Use CREATE INDEX ASYNC instead of CONCURRENTLY.",
            FixResult::Fixed("Replaced CONCURRENTLY with ASYNC".to_string()),
        ));
    } else if !ci.r#async {
        ci.r#async = true;
        let idx_name = ci.name.as_ref().map(|n| n.to_string()).unwrap_or_default();
        diagnostics.push(error(
            LintRule::IndexAsync,
            find_line(raw_sql, "index"),
            format!(
                "CREATE INDEX without ASYNC is not supported in DSQL.{}",
                if !idx_name.is_empty() {
                    format!(" Index: {idx_name}")
                } else {
                    String::new()
                }
            ),
            "Use `CREATE INDEX ASYNC ...` instead.",
            FixResult::Fixed("Added ASYNC keyword to CREATE INDEX".to_string()),
        ));
    }

    let using_type = ci.using.take().or_else(|| {
        ci.index_options.iter().find_map(|opt| {
            if let IndexOption::Using(idx_type) = opt {
                Some(idx_type.clone())
            } else {
                None
            }
        })
    });
    if using_type.is_some() {
        ci.index_options
            .retain(|opt| !matches!(opt, IndexOption::Using(_)));
    }
    if let Some(index_type) = using_type {
        let index_type_str = index_type.to_string();
        let is_btree = index_type_str.eq_ignore_ascii_case("btree");
        let fix_result = if is_btree {
            FixResult::Fixed(format!(
                "Removed USING {index_type_str} clause (btree is the default)"
            ))
        } else {
            FixResult::FixedWithWarning(format!(
                "Removed USING {index_type_str} clause — DSQL only supports btree indexes"
            ))
        };
        diagnostics.push(error(
            LintRule::IndexUsing,
            find_line(raw_sql, "using"),
            format!("DSQL does not support the USING clause in CREATE INDEX (found USING {index_type_str}). Remove it — btree is used automatically."),
            "Remove the USING clause. DSQL uses btree indexes by default.",
            fix_result,
        ));
    }

    // Expression indexes — Unfixable
    for col in &ci.columns {
        if !matches!(&col.column.expr, Expr::Identifier(_)) {
            diagnostics.push(error(
                LintRule::IndexExpression,
                find_line(raw_sql, "index"),
                "Expression indexes are not supported in DSQL. Only simple column references are allowed.",
                "Add a stored computed column and index that instead, or handle in application layer.",
                FixResult::Unfixable,
            ));
            break;
        }
    }

    // Partial indexes — Unfixable
    if ci.predicate.is_some() {
        diagnostics.push(error(
            LintRule::IndexPartial,
            find_line(raw_sql, "where"),
            "Partial indexes (CREATE INDEX ... WHERE) are not supported in DSQL.",
            "Create a full index instead, or filter in queries.",
            FixResult::Unfixable,
        ));
    }
}

fn check_truncate(stmt: &mut Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if matches!(stmt, Statement::Truncate(_)) {
        diagnostics.push(error(
            LintRule::Truncate,
            find_line(raw_sql, "truncate"),
            "TRUNCATE is not supported in DSQL.",
            "Use DELETE FROM table_name instead.",
            FixResult::Unfixable,
        ));
    }
}

/// Validate CACHE values in sequence options.
fn validate_cache_options(
    cache_rule: LintRule,
    opts: &mut [SequenceOptions],
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    for opt in opts.iter_mut() {
        let cache_expr = match opt {
            SequenceOptions::Cache(expr) => expr,
            _ => continue,
        };

        let cache_val = match cache_expr {
            Expr::Value(ValueWithSpan {
                value: Value::Number(n, _),
                ..
            }) => n.parse::<i64>().ok(),
            Expr::UnaryOp {
                op: UnaryOperator::Minus,
                expr,
            } => {
                if let Expr::Value(ValueWithSpan {
                    value: Value::Number(n, _),
                    ..
                }) = expr.as_ref()
                {
                    n.parse::<i64>().ok().map(|v| -v)
                } else {
                    None
                }
            }
            Expr::UnaryOp {
                op: UnaryOperator::Plus,
                expr,
            } => {
                if let Expr::Value(ValueWithSpan {
                    value: Value::Number(n, _),
                    ..
                }) = expr.as_ref()
                {
                    n.parse::<i64>().ok()
                } else {
                    None
                }
            }
            _ => None,
        };

        match cache_val {
            Some(v) if v == 1 || v >= 65536 => {} // valid
            Some(v) => {
                *opt = cache_1_option();
                diagnostics.push(error(
                    cache_rule,
                    find_line(raw_sql, "cache"),
                    format!(
                        "CACHE value {v} is invalid in DSQL. Only CACHE 1 or CACHE >= 65536 are allowed."
                    ),
                    "Use CACHE 1 for sequential behavior or CACHE 65536+ for high-throughput.",
                    FixResult::FixedWithWarning(format!("Changed CACHE {v} to CACHE 1 — consider CACHE 65536 for high-throughput workloads")),
                ));
            }
            None => {
                diagnostics.push(error(
                    cache_rule,
                    find_line(raw_sql, "cache"),
                    format!(
                        "CACHE value '{cache_expr}' could not be validated for DSQL. Only CACHE 1 or CACHE >= 65536 are allowed."
                    ),
                    "Use CACHE 1 for sequential behavior or CACHE 65536+ for high-throughput.",
                    FixResult::Unfixable,
                ));
            }
        }
    }
}

fn check_create_sequence(stmt: &mut Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    let Statement::CreateSequence {
        data_type,
        sequence_options,
        ..
    } = stmt
    else {
        return;
    };

    if let Some(dt) = data_type {
        let is_bigint = matches!(dt, DataType::BigInt(_) | DataType::Int8(_));
        if !is_bigint {
            let old_type = dt.to_string();
            *dt = DataType::BigInt(None);
            diagnostics.push(error(
                LintRule::SequenceType,
                find_line(raw_sql, "create sequence"),
                format!(
                    "CREATE SEQUENCE with type {old_type} is not supported in DSQL. Only BIGINT is supported."
                ),
                "Use AS BIGINT or omit the type clause (defaults to BIGINT).",
                FixResult::Fixed(format!("Changed sequence type from {old_type} to BIGINT")),
            ));
        }
    }

    validate_cache_options(
        LintRule::SequenceCache,
        sequence_options,
        raw_sql,
        diagnostics,
    );
}

fn check_unsupported_statements(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    match stmt {
        Statement::CreateView(cv) if cv.temporary => {
            cv.temporary = false;
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line_any(raw_sql, &["temporary view", "temp view"]),
                "CREATE TEMPORARY VIEW is not supported in DSQL.",
                "Use a regular CREATE VIEW instead.",
                FixResult::FixedWithWarning("Removed TEMPORARY keyword from view".into()),
            ));
        }

        Statement::CreateView(cv) if cv.materialized => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "materialized view"),
                "CREATE MATERIALIZED VIEW is not supported in DSQL.",
                "Use a regular CREATE VIEW instead.",
                FixResult::Unfixable,
            ));
        }

        Statement::CreateTrigger(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "create trigger"),
                "CREATE TRIGGER is not supported in DSQL.",
                "Implement trigger logic in application layer.",
                FixResult::Unfixable,
            ));
        }
        Statement::CreateExtension(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "create extension"),
                "CREATE EXTENSION is not supported in DSQL.",
                "Extensions not available in DSQL.",
                FixResult::Unfixable,
            ));
        }
        Statement::CreateFunction(cf) => {
            let is_sql_language = cf
                .language
                .as_ref()
                .map(|l| l.value.eq_ignore_ascii_case("sql"))
                .unwrap_or(true);
            if !is_sql_language {
                let lang_info = cf
                    .language
                    .as_ref()
                    .map(|l| format!(" (LANGUAGE {})", l.value))
                    .unwrap_or_default();
                diagnostics.push(error(
                    LintRule::UnsupportedStatement,
                    find_line(raw_sql, "create function"),
                    format!(
                        "CREATE FUNCTION{lang_info} is not supported in DSQL. Only LANGUAGE SQL is allowed."
                    ),
                    "Use LANGUAGE SQL or implement in application layer.",
                    FixResult::Unfixable,
                ));
            }
        }
        Statement::CreateProcedure { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "create procedure"),
                "CREATE PROCEDURE is not supported in DSQL.",
                "Implement in application layer.",
                FixResult::Unfixable,
            ));
        }

        Statement::CreateDatabase { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "create database"),
                "CREATE DATABASE is not supported in DSQL. Each cluster provides a single 'postgres' database.",
                "Use separate DSQL clusters for logical separation, or use schemas within a single cluster.",
                FixResult::Unfixable,
            ));
        }

        Statement::CreatePolicy(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "create policy"),
                "CREATE POLICY (Row-Level Security) is not supported in DSQL.",
                "Implement row-level access control in the application layer.",
                FixResult::Unfixable,
            ));
        }

        Statement::Savepoint { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "savepoint"),
                "SAVEPOINT is not supported in DSQL.",
                "Restructure logic to use separate transactions instead of partial rollbacks.",
                FixResult::Unfixable,
            ));
        }

        Statement::ReleaseSavepoint { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "release savepoint"),
                "RELEASE SAVEPOINT is not supported in DSQL.",
                "Restructure logic to use separate transactions instead of partial rollbacks.",
                FixResult::Unfixable,
            ));
        }

        Statement::Rollback {
            savepoint: Some(_), ..
        } => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "savepoint"),
                "ROLLBACK TO SAVEPOINT is not supported in DSQL.",
                "Restructure logic to use separate transactions instead of partial rollbacks.",
                FixResult::Unfixable,
            ));
        }

        Statement::Declare { stmts } => {
            for d in stmts {
                if matches!(d.declare_type, Some(DeclareType::Cursor)) {
                    diagnostics.push(error(
                        LintRule::UnsupportedStatement,
                        find_line(raw_sql, "cursor"),
                        "DECLARE CURSOR is not supported in DSQL.",
                        "Use LIMIT/OFFSET pagination or application-side cursoring.",
                        FixResult::Unfixable,
                    ));
                    break;
                }
            }
        }

        Statement::CreateType { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "create type"),
                "CREATE TYPE is not supported in DSQL.",
                "Use CHECK constraints for enum-like validation, or TEXT with application-layer validation.",
                FixResult::Unfixable,
            ));
        }

        Statement::CreateServer(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "create server"),
                "CREATE SERVER is not supported in DSQL.",
                "Access external data sources from the application layer.",
                FixResult::Unfixable,
            ));
        }

        Statement::Vacuum(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "vacuum"),
                "VACUUM is not supported in DSQL.",
                "Remove VACUUM commands. DSQL manages maintenance automatically.",
                FixResult::Unfixable,
            ));
        }

        Statement::AlterIndex { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "alter index"),
                "ALTER INDEX is not supported in DSQL.",
                "Drop and recreate the index with the desired properties.",
                FixResult::Unfixable,
            ));
        }

        Statement::Copy {
            target: target @ (CopyTarget::File { .. } | CopyTarget::Program { .. }),
            ..
        } => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "copy"),
                format!("COPY with {target} is not supported in DSQL. Only STDIN/STDOUT are allowed."),
                "Use COPY ... FROM STDIN / COPY ... TO STDOUT, or load data from the application layer.",
                FixResult::Unfixable,
            ));
        }

        Statement::Lock { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedStatement,
                find_line(raw_sql, "lock"),
                "LOCK TABLE is not supported in DSQL.",
                "Remove LOCK TABLE statements. DSQL uses optimistic concurrency control.",
                FixResult::Unfixable,
            ));
        }

        _ => {}
    }
}

/// Transaction isolation level — only REPEATABLE READ is supported.
fn check_transaction_isolation(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let (modes, is_set_transaction) = match stmt {
        Statement::StartTransaction { modes, .. } => (modes, false),
        Statement::Set(Set::SetTransaction { modes, .. }) => (modes, true),
        _ => return,
    };

    if is_set_transaction {
        diagnostics.push(error(
            LintRule::SetTransaction,
            find_line(raw_sql, "set transaction"),
            "SET TRANSACTION is not supported in DSQL.",
            "Use `BEGIN ISOLATION LEVEL REPEATABLE READ` instead.",
            FixResult::Unfixable,
        ));
        return;
    }

    for mode in modes.iter_mut() {
        if let TransactionMode::IsolationLevel(level) = mode {
            if !matches!(level, TransactionIsolationLevel::RepeatableRead) {
                let old_level = level.to_string();
                *level = TransactionIsolationLevel::RepeatableRead;
                diagnostics.push(error(
                    LintRule::TransactionIsolation,
                    find_line(raw_sql, "isolation"),
                    format!(
                        "Transaction isolation level {old_level} is not supported in DSQL. Only REPEATABLE READ is supported."
                    ),
                    "Remove the isolation level clause, or use ISOLATION LEVEL REPEATABLE READ.",
                    FixResult::Fixed(format!("Changed isolation level from {old_level} to REPEATABLE READ")),
                ));
            }
        }
    }
}

/// CREATE SEQUENCE without explicit CACHE clause.
fn check_sequence_cache_missing(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let Statement::CreateSequence {
        sequence_options, ..
    } = stmt
    else {
        return;
    };
    let has_cache = sequence_options
        .iter()
        .any(|o| matches!(o, SequenceOptions::Cache(_)));
    if !has_cache {
        sequence_options.push(cache_1_option());
        diagnostics.push(error(
            LintRule::SequenceCacheMissing,
            find_line(raw_sql, "create sequence"),
            "CREATE SEQUENCE without explicit CACHE clause is not supported in DSQL.",
            "Add an explicit CACHE 1 or CACHE 65536 clause.",
            FixResult::Fixed("Added CACHE 1 to CREATE SEQUENCE".to_string()),
        ));
    }
}

/// Identity column without explicit CACHE clause.
fn check_identity_cache_missing(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let columns: Vec<&mut ColumnDef> = match stmt {
        Statement::CreateTable(ct) => ct.columns.iter_mut().collect(),
        _ => return,
    };
    for col in columns {
        for opt_def in &mut col.options {
            if let ColumnOption::Generated {
                generated_as: GeneratedAs::Always | GeneratedAs::ByDefault,
                sequence_options,
                ..
            } = &mut opt_def.option
            {
                let has_cache = sequence_options.as_ref().is_some_and(|opts| {
                    opts.iter().any(|o| matches!(o, SequenceOptions::Cache(_)))
                });
                if !has_cache {
                    let cache_opt = cache_1_option();
                    match sequence_options {
                        Some(opts) => opts.push(cache_opt),
                        None => *sequence_options = Some(vec![cache_opt]),
                    }
                    diagnostics.push(error(
                        LintRule::IdentityCacheMissing,
                        find_line(raw_sql, &col.name.to_string().to_lowercase()),
                        format!(
                            "Identity column `{}` without explicit CACHE clause is not supported in DSQL.",
                            col.name
                        ),
                        "Add an explicit CACHE 1 or CACHE 65536 clause to the identity definition.",
                        FixResult::Fixed(format!("Added CACHE 1 to identity column `{}`", col.name)),
                    ));
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlparser::dialect::PostgreSqlDialect;
    use sqlparser::parser::Parser;

    fn parse_and_check(sql: &str) -> Vec<Diagnostic> {
        let dialect = PostgreSqlDialect {};
        let mut stmts = Parser::parse_sql(&dialect, sql).expect("SQL should parse");
        let mut diags = Vec::new();
        for stmt in &mut stmts {
            check(stmt, sql, &mut diags);
        }
        diags
    }

    const VALIDATED_SUGGESTIONS: &[&str] = &[
        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
        "CREATE INDEX ASYNC ...",
    ];

    #[test]
    fn suggested_replacements_are_dsql_valid() {
        for suggestion in VALIDATED_SUGGESTIONS {
            if suggestion.starts_with("CREATE") {
                let sql = "CREATE INDEX ASYNC idx_test ON t(col);";
                let diags = crate::lint::lint_sql(sql);
                assert!(
                    !diags.iter().any(|d| d.message.contains("not supported")),
                    "Suggested command triggers lint errors!\n  Suggestion: {suggestion}\n  Errors: {diags:?}"
                );
            } else {
                let sql = format!("CREATE TABLE _test (id {suggestion} PRIMARY KEY);");
                let diags = crate::lint::lint_sql(&sql);
                let errors: Vec<_> = diags
                    .iter()
                    .filter(|d| d.message.contains("not supported"))
                    .collect();
                assert!(
                    errors.is_empty(),
                    "Suggested type is not DSQL-valid!\n  Type: {suggestion}\n  Errors: {errors:?}"
                );
            }
        }
    }

    #[test]
    fn all_suggested_replacements_are_covered() {
        let inputs = &[
            "CREATE TABLE t (id SERIAL PRIMARY KEY);",
            "CREATE TABLE t (id BIGSERIAL PRIMARY KEY);",
            "CREATE TABLE t (id SMALLSERIAL PRIMARY KEY);",
            "CREATE INDEX idx ON t(col);",
        ];
        let mut found: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
        for sql in inputs {
            for d in crate::lint::lint_sql(sql) {
                if let (Some(a), Some(b)) = (d.suggestion.find('`'), d.suggestion.rfind('`')) {
                    if a < b {
                        found.insert(d.suggestion[a + 1..b].to_string());
                    }
                }
            }
        }
        for replacement in &found {
            assert!(
                VALIDATED_SUGGESTIONS.iter().any(|s| {
                    s == replacement
                        || (s.ends_with("...") && replacement.starts_with(&s[..s.len() - 3]))
                }),
                "Suggestion `{replacement}` emitted by linter but not in VALIDATED_SUGGESTIONS"
            );
        }
    }

    #[test]
    fn plpgsql_detected_and_includes_language_name() {
        let sql = "CREATE FUNCTION inc(v INT) RETURNS INT AS $$ BEGIN RETURN v+1; END; $$ LANGUAGE plpgsql;";
        let diags = parse_and_check(sql);
        assert!(diags.iter().any(|d| d.message.contains("LANGUAGE plpgsql")));
    }

    #[test]
    fn sql_function_not_flagged() {
        let sql =
            "CREATE FUNCTION add(a INT, b INT) RETURNS INT AS $$ SELECT a + b; $$ LANGUAGE SQL;";
        let diags = parse_and_check(sql);
        assert!(!diags.iter().any(|d| d.message.contains("FUNCTION")));
    }

    #[test]
    fn function_without_language_not_flagged() {
        let sql = "CREATE FUNCTION add(INTEGER, INTEGER) RETURNS INTEGER AS 'select $1 + $2;'";
        let diags = parse_and_check(sql);
        assert!(
            !diags.iter().any(|d| d.message.contains("FUNCTION")),
            "Function without LANGUAGE clause should default to SQL and not be flagged: {diags:?}"
        );
    }

    #[test]
    fn serial_with_references_reports_both() {
        let sql = "CREATE TABLE t (id SERIAL REFERENCES other(id));";
        let diags = parse_and_check(sql);
        assert!(diags.iter().any(|d| d.message.contains("SERIAL")));
        assert!(diags.iter().any(|d| d.message.contains("FOREIGN KEY")));
    }

    #[test]
    fn create_procedure_detected() {
        let sql = "CREATE PROCEDURE do_stuff() AS BEGIN SELECT 1; END";
        let diags = parse_and_check(sql);
        assert!(diags.iter().any(|d| d.message.contains("PROCEDURE")));
    }

    #[test]
    fn multiple_references_report_distinct_lines() {
        let sql =
            "CREATE TABLE t (\n    a INT REFERENCES foo(id),\n    b INT REFERENCES bar(id)\n);";
        let diags = parse_and_check(sql);
        let fk_lines: Vec<usize> = diags
            .iter()
            .filter(|d| d.message.contains("FOREIGN KEY"))
            .map(|d| d.line)
            .collect();
        assert_eq!(fk_lines.len(), 2);
        assert_ne!(fk_lines[0], fk_lines[1]);
    }

    #[test]
    fn multiline_index_still_caught() {
        let sql = "CREATE INDEX idx_orders\n  ON orders(customer_id);";
        let diags = parse_and_check(sql);
        assert!(diags.iter().any(|d| d.message.contains("ASYNC")));
    }

    #[test]
    fn comment_index_not_flagged() {
        let sql = "-- CREATE INDEX idx_foo ON bar(baz);\nSELECT 1;";
        let diags = parse_and_check(sql);
        assert!(!diags.iter().any(|d| d.message.contains("ASYNC")));
    }
}
