/// Column types that DSQL supports. Shared between unit and cluster tests
/// to keep the two lists from drifting.
///
/// Source: https://docs.aws.amazon.com/aurora-dsql/latest/userguide/
///         working-with-postgresql-compatibility-supported-data-types.html
pub const SUPPORTED_TYPES: &[(&str, &str)] = &[
    // Numeric
    ("smallint", "SMALLINT"),
    ("int2", "INT2"),
    ("integer", "INTEGER"),
    ("int", "INT"),
    ("int4", "INT4"),
    ("bigint", "BIGINT"),
    ("int8", "INT8"),
    ("real", "REAL"),
    ("float4", "FLOAT4"),
    ("double-precision", "DOUBLE PRECISION"),
    ("float8", "FLOAT8"),
    ("numeric", "NUMERIC(10,2)"),
    ("decimal", "DECIMAL(18,6)"),
    ("dec", "DEC(5,2)"),
    // Character
    ("char", "CHAR(10)"),
    ("character", "CHARACTER(20)"),
    ("varchar", "VARCHAR(255)"),
    ("character-varying", "CHARACTER VARYING(100)"),
    ("text", "TEXT"),
    ("bpchar", "BPCHAR(50)"),
    // Date/time
    ("date", "DATE"),
    ("time", "TIME"),
    ("time-tz", "TIME WITH TIME ZONE"),
    ("timestamp", "TIMESTAMP"),
    ("timestamp-tz", "TIMESTAMP WITH TIME ZONE"),
    ("interval", "INTERVAL"),
    // Miscellaneous
    ("boolean", "BOOLEAN"),
    ("bool", "BOOL"),
    ("bytea", "BYTEA"),
    ("uuid", "UUID"),
    // Identity columns
    (
        "identity-always",
        "BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 1)",
    ),
    (
        "identity-by-default",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
    ),
    (
        "identity-cache-65536",
        "BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 65536)",
    ),
    (
        "identity-by-default-cache-65536",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 65536)",
    ),
];

/// Single statements that must lint clean AND execute on a real DSQL cluster.
/// Shared between unit and cluster tests so the two lists can't drift.
///
/// Each entry: (label, sql, setup_sql, cleanup_sql).
pub const CLEAN_STATEMENTS: &[(&str, &str, &str, &str)] = &[
    (
        "create-view",
        "CREATE VIEW _clean_view AS SELECT 1;",
        "",
        "DROP VIEW IF EXISTS _clean_view;",
    ),
    (
        "alter-add-col",
        "ALTER TABLE _clean_base ADD COLUMN description TEXT;",
        "",
        "ALTER TABLE _clean_base DROP COLUMN IF EXISTS description;",
    ),
    (
        "insert",
        "INSERT INTO _clean_base (id, name) VALUES (1, 'test');",
        "",
        "",
    ),
    ("select", "SELECT * FROM _clean_base WHERE id = 1;", "", ""),
    (
        "update",
        "UPDATE _clean_base SET name = 'updated' WHERE id = 1;",
        "",
        "",
    ),
    ("delete", "DELETE FROM _clean_base WHERE id = 1;", "", ""),
    (
        "begin-repeatable-read",
        "BEGIN ISOLATION LEVEL REPEATABLE READ;",
        "",
        "ROLLBACK;",
    ),
    ("begin-plain", "BEGIN;", "", "ROLLBACK;"),
    (
        "create-view-v2",
        "CREATE VIEW _clean_view2 AS SELECT 1;",
        "",
        "DROP VIEW IF EXISTS _clean_view2;",
    ),
    (
        "insert-string-with-sql-keywords",
        "INSERT INTO _clean_base (id, name) VALUES (2, 'TRUNCATE TABLE foo; CREATE TRIGGER bar');",
        "",
        "",
    ),
];

use dsql_lint::LintRule;

/// Maps every lint rule to representative SQL that triggers it, plus the
/// expected error substring.
///
/// Adding a new `LintRule` variant without a match arm here is a compile error.
/// Return `None` for rules that don't need cluster validation (e.g. parse errors).
#[allow(dead_code)]
pub fn cluster_test_for_rule(rule: LintRule) -> Option<(&'static str, &'static str)> {
    match rule {
        LintRule::SerialType => Some(("CREATE TABLE _r (id SERIAL PRIMARY KEY);", "SERIAL")),
        LintRule::JsonType => Some(("CREATE TABLE _r (id INT, data JSON);", "JSON")),
        LintRule::ArrayType => Some(("CREATE TABLE _r (id INT, tags TEXT[]);", "array")),
        LintRule::ForeignKey => Some((
            "CREATE TABLE _r (id INT, cid INT REFERENCES _clust_base(id));",
            "FOREIGN KEY",
        )),
        LintRule::TempTable => Some(("CREATE TEMP TABLE _r (id INT);", "TEMPORARY")),
        LintRule::PartitionBy => Some((
            "CREATE TABLE _r (id INT, d DATE) PARTITION BY RANGE (d);",
            "PARTITION",
        )),
        LintRule::Inherits => Some((
            "CREATE TABLE _r (extra INT) INHERITS (_clust_base);",
            "INHERITS",
        )),
        LintRule::CreateTableAs => Some(("CREATE TABLE _r AS SELECT 1 AS id;", "CREATE TABLE AS")),
        LintRule::Tablespace => Some((
            "CREATE TABLE _r (id INT) TABLESPACE my_space;",
            "TABLESPACE",
        )),
        LintRule::IdentityType => Some((
            "CREATE TABLE _r (id INTEGER GENERATED ALWAYS AS IDENTITY);",
            "Identity column",
        )),
        LintRule::IdentityCache => Some((
            "CREATE TABLE _r (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 100));",
            "CACHE value",
        )),
        LintRule::IdentityCacheMissing => Some((
            "CREATE TABLE _r (id BIGINT GENERATED ALWAYS AS IDENTITY);",
            "CACHE",
        )),
        LintRule::IndexAsync => Some(("CREATE INDEX _r_idx ON _clust_base(col);", "ASYNC")),
        LintRule::IndexConcurrently => Some((
            "CREATE INDEX CONCURRENTLY _r_idx ON _clust_base(col);",
            "CONCURRENTLY",
        )),
        LintRule::IndexUsing => Some((
            "CREATE INDEX ASYNC _r_idx ON _clust_base USING btree(col);",
            "USING",
        )),
        LintRule::IndexExpression => Some((
            "CREATE INDEX ASYNC _r_idx ON _clust_base(lower(col));",
            "Expression",
        )),
        LintRule::IndexPartial => Some((
            "CREATE INDEX ASYNC _r_idx ON _clust_base(col) WHERE col > 0;",
            "Partial",
        )),
        LintRule::Truncate => Some(("TRUNCATE TABLE _clust_base;", "TRUNCATE")),
        LintRule::SequenceType => Some((
            "CREATE SEQUENCE _r_seq AS INTEGER CACHE 1;",
            "CREATE SEQUENCE with type",
        )),
        LintRule::SequenceCache => Some(("CREATE SEQUENCE _r_seq CACHE 100;", "CACHE value")),
        LintRule::SequenceCacheMissing => Some(("CREATE SEQUENCE _r_seq;", "CACHE")),
        LintRule::AddColumnConstraint => Some((
            "ALTER TABLE _clust_base ADD COLUMN status VARCHAR(50) DEFAULT 'pending';",
            "ADD COLUMN",
        )),
        LintRule::TransactionIsolation => {
            Some(("BEGIN ISOLATION LEVEL SERIALIZABLE;", "isolation level"))
        }
        LintRule::SetTransaction => Some((
            "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;",
            "SET TRANSACTION",
        )),
        LintRule::UnsupportedAlterTableOp => {
            Some(("ALTER TABLE _clust_base DROP COLUMN col;", "DROP COLUMN"))
        }
        LintRule::UnsupportedStatement => Some((
            "CREATE TRIGGER trg AFTER INSERT ON _clust_base FOR EACH ROW EXECUTE FUNCTION f();",
            "TRIGGER",
        )),
        LintRule::MultiDdlTransaction => Some((
            "BEGIN;\nCREATE TABLE _r_a (id INT);\nCREATE TABLE _r_b (id INT);\nCOMMIT;",
            "DDL statements",
        )),
        LintRule::ParseError => None,
        _ => None,
    }
}

/// Multi-statement SQL that must lint clean AND execute on a real DSQL cluster.
pub const CLEAN_MULTI_STATEMENT_CASES: &[(&str, &str, &str)] = &[
    (
        "single-ddl-in-txn",
        "CREATE TABLE _clust_txn_a (id INT);\nBEGIN;\nCREATE TABLE _clust_txn_b (id INT);\nCOMMIT;",
        "DROP TABLE IF EXISTS _clust_txn_a; DROP TABLE IF EXISTS _clust_txn_b;",
    ),
    (
        "bare-ddl-no-txn",
        "CREATE TABLE _clust_txn_c (id INT);\nCREATE TABLE _clust_txn_d (id INT);",
        "DROP TABLE IF EXISTS _clust_txn_c; DROP TABLE IF EXISTS _clust_txn_d;",
    ),
    (
        "dml-only-in-txn",
        "BEGIN;\nSELECT 1;\nCOMMIT;",
        "",
    ),
    (
        "ddl-plus-dml-in-txn",
        "CREATE TABLE _clust_txn_e (id INT);\nBEGIN;\nCREATE TABLE _clust_txn_f (id INT);\nINSERT INTO _clust_txn_e VALUES (1);\nCOMMIT;",
        "DROP TABLE IF EXISTS _clust_txn_e; DROP TABLE IF EXISTS _clust_txn_f;",
    ),
    (
        "empty-txn",
        "BEGIN;\nCOMMIT;",
        "",
    ),
    (
        "separate-single-ddl-txns",
        "BEGIN;\nCREATE TABLE _clust_txn_g (id INT);\nCOMMIT;\nBEGIN;\nCREATE TABLE _clust_txn_h (id INT);\nCOMMIT;",
        "DROP TABLE IF EXISTS _clust_txn_g; DROP TABLE IF EXISTS _clust_txn_h;",
    ),
];
